In [3]:
class classname():
    def test(self):
        print("test");
        return
obj=classname()
obj.test()

test


In [8]:
def test():
    print("test() for function")
    return
test()

test() for function


In [9]:
class demo1:
    def fact(self,n):
        fact=1;
        while(n!=0):
            fact=fact*n;
            n=n-1;
        return fact
p1=demo1()
print(p1.fact(5))

120


In [10]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p2
        self.p2=p1
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(10,20))

30


In [ ]:
#arrange()-- particular
#numpy --arrange(start,end,step)
#start -- value
#end -- value
#step --gap between one value to another value

In [12]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("FIRST ROW:",a1[1])

FIRST ROW: [4 5 6]


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print("FIRST COLUMN:",a1[:,1])

FIRST COLUMN: [2 5]


In [17]:
a1=np.array([(1,2,3),(4,5,6)])
print("FIRST COLUMN:",a1[:,2])

FIRST COLUMN: [3 6]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print("FIRST ELEMENT:",a1[0][1])

FIRST ELEMENT: 2


In [ ]:
#SOME MATH OPERATIONS ON THE GIVEN RANDOM NUMBERS
#MIN     --returns the least no.
#MAX     --returns the large no.
#MEAN    --mean
#MEDIAN  --median

In [20]:
a1=np.random.normal(5,1,10)
print(a1)

[3.02825886 5.81267203 4.98497646 5.13227353 5.33235732 5.85470965
 3.02573372 4.3851351  4.37101871 5.60471182]


In [21]:
a1=np.random.normal(5,1,10)
print(a1)
print("Minvalue=",np.min(a1))
print("Maxvalue=",np.max(a1))
print("Meanvalue=",np.mean(a1))
print("Medianvalue=",np.median(a1))

[3.13281268 6.80341019 4.56272357 3.41127921 5.50651587 3.92490148
 7.08079645 4.72529153 3.32446358 4.49492452]
Minvalue= 3.13281267762852
Maxvalue= 7.080796449723348
Meanvalue= 4.696711908415774
Medianvalue= 4.528824045816064


In [22]:
#MULTIPLICATION OF 1D ARRAYS
#numpy.dot(x,y) --
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [24]:
c1=np.array([(1,2),(3,5)])
c2=np.array([(4,5),(3,2)])
np.dot(c1,c2)

array([[10,  9],
       [27, 25]])

In [26]:
b1=np.array([(1,2),(3,5)])
b2=np.array([(4,5),(3,2)])
np.matmul(c1,c2)

array([[10,  9],
       [27, 25]])

In [1]:
import pandas as pd
dict = {"name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "email id":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
        "mobileno.":["90909090903","9879587567","9865475364","96755463746","98675464847","9856434256"],
        "address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

     name          email id    mobileno. address
0    Anil    anil@gmail.com  90909090903     hyd
1   Akhil   akhil@gmail.com   9879587567     hyd
2  Dinesh  dinesh@gmail.com   9865475364     hyd
3  Harsha  harsha@gmail.com  96755463746     hyd
4    Ajay    ajay@gmail.com  98675464847     hyd
5  Kranth  kranth@gmail.com   9856434256     hyd
